config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:create, :new, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
    resource :sessions, only: [:update]
  end

  

  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include MoviesHelper
  def index
    @movie = Movie.new
    @movies = Movie.all
    if params[:term].present?
      @movies = @movies.title_or_director_filter(params[:term])
    end
    if params[:duration].to_i > 0
      @movies = @movies.duration_filter(params[:duration])
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      respond_to do |format|
        format.html { redirect_to movies_path}
        # format.json {render json: @movie}
        format.json do
          @json_movie = @movie.as_json(methods: :average_review)
          @json_movie[:formatted_date] = formatted_date(@movie.release_date)
          @json_movie[:image_src] = @movie.poster_image_url_url(:thumb) 
        #   # 2) slap a bunch of extra data on there, like 
        #   #      @movie.average_review
        #   #      link_to image_tag(movie.poster_image_url_url(:thumb))
        #   #       etc
        #   # 3) send that json thing back to the client
          render json: @json_movie
        end
      end
    else
      render json: {message: "Not created successfully"}.to_json
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :remote_poster_image_url_url
    )
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d %Y")
  end

end

app/views/movies/_form.html.erb
<%= form_for @movie, html: {multipart: true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster_image_url %> <br>
    <%= f.file_field :poster_image_url %>
  </div>
  <div>
    <%= f.label :remote_poster_image_url_url, "OR use url" %><br>
    <%= f.text_field :remote_poster_image_url_url %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id='<%=movie.id%>'class="container-fluid">
  <div class="row">
    <div class="col-md-4">
    <%= link_to image_tag(movie.poster_image_url_url(:thumb)), movie_path(movie) %>
    </div>
    <div class="col-mid-8">
      <h2><%= link_to movie.title, movie_path(movie) %></h2>
      <h3><%= formatted_date(movie.release_date) %></h3>
      <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
      <p><%= movie.description %></p>
      <p class="average-rating">Average rating: <%= movie.review_average %>/10</p>
    </div>
  </div>
  <hr>
</div>

app/views/movies/_search.html.erb
<div class="container">
  <%= form_tag movies_path, method: "GET" do %>
    <div class="row">
    <%= text_field_tag :term, params[:term], placeholder: "Search For A Movie" %>
    </div>
    <br>
    <div class="row">
    <%=select_tag(:duration, options_for_select([['Select an option', 0], ['Under 90 Minutes', 1], ['Between 90 and 120 Minutes', 2], ['Over 120 Minutes', 3]]))%>
    </div> <br>
    <%= submit_tag "Search", name: nil %>
  <% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie!</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<header class="intro-header">
  <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <div class="site-heading">
              <br><br><br>
              <h1 class="header-text-blur text-center">Rotten Mangoes</h1>
              <hr class="small-hr">
              </div>
              <h1 class="header-text-blur text-center small">Your go-to site for movie reviews</h1>
          </div>
      </div>
  </div>
</header>


<div class= "container"> 
  <br><br>
    <button id="show-form" class="btn-link center-block"> Submit a new movie! </button>
  <div id="new-movie-form" class="hidden">
    <%= form_for @movie, html: {multipart: true} do |f| %>
      <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :release_date %><br>
        <%= f.date_field :release_date %>
      </div>
      <div>
        <%= f.label :director %><br>
        <%= f.text_field :director %>
      </div>
      <div>
        <%= f.label :runtime_in_minutes %><br>
        <%= f.number_field :runtime_in_minutes %>
      </div>
      <div>
        <%= f.label :poster_image_url %> <br>
        <%= f.file_field :poster_image_url %>
      </div>
      <div>
        <%= f.label :remote_poster_image_url_url, "OR use url" %><br>
        <%= f.text_field :remote_poster_image_url_url %>
      </div>
      <div>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit "Submit" %> 
      </div>
    <% end %>
  </div> <br>

  <hr>
  <div id="movies">
    <%= render @movies %> <!-- collection weird stuff going on -->
  </div>

</div>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<div class="container">
  <div style="display: none;">
  <%= link_to "Back to all movies", movies_path %><br/>
  </div> <br>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag(@movie.poster_image_url_url(:big_thumb))%>
    </div>
    <div class="col-md-8">
      <h2><%= @movie.title %> (<%= link_to "Edit", edit_movie_path(@movie) %>, <%= link_to "Delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
      <h3><%=formatted_date(@movie.release_date)%></h3>
      <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4><hr>
      <p><%= @movie.description %></p>
      <p class="biggify"><%= @movie.review_average %>/10</p>
    </div>
  </div>
  <hr>

  <h3 class="text-center"><u>Reviews of <%= @movie.title %></u></h3>
  <% if current_user %>
    <% @movie.reviews.each do |review| %>
      <p><%= review.text %></p>
      <p><%= review.rating_out_of_ten %>/10</p>
      <small>- <%= link_to review.user.full_name, user_path(review.user) %></small><br/><hr>
    <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
  <% else %>
    <p>Please <%= link_to "log in", new_sessions_path %> to see reviews and add your own.</p> 
  <% end %>
</div>