config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:create, :new, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
    resource :sessions, only: [:update]
  end

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :only_allow_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "You have successfully created #{@user.full_name}"
    else
      render :'admin/users/new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path(@user), notice: "#{@user.full_name} has been successfully updated"
    else
      render :'admin/users/edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.destroyed_email(@user).deliver
    @user.destroy
    redirect_to admin_users_path, notice: "That fool was successfully taken care of..."
  end


  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :is_admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id 
      redirect_to movies_path, notice: "You're an absolute beauty, #{@user.firstname}"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>

<div>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
  <%= f.label :firstname, "First Name" %><br>
  <%= f.text_field :firstname %><br>
<div>
  <%= f.label :lastname, "Last Name" %><br>
  <%= f.text_field :lastname %>
</div>
  <%= f.label :password %><br>
  <%= f.password_field :password %>
<div>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
</div>
<div>
  <%= f.label :is_admin, "Admin" %><br>
  <%= f.check_box :is_admin %>
</div>
<div><%= f.submit "Submit" %></div>

<% end %>  

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h2> EDIT THIS USER </h2>
<% if @user.errors.any? %>
  <div>
    <%= pluralize(@user.errors.count, "error") %> prevented the account from being created: <!-- cool method pluralize -->
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin Page </h1>

<%= link_to "Back to all movies", movies_path %> <br>
<%= link_to "Create a new User" , new_admin_user_path %>
<hr>
<% @users.each do |user| %>
  <p> Username: <%= user.full_name %> <%= link_to "Edit", edit_admin_user_path(user) %>
  <%= link_to "Delete", admin_user_path(user), method: :delete, data: { confirm: 'You sure?' } %></p>
  <%= link_to "See more details", admin_user_path(user) %>
  <hr>


<% end %>

app/views/admin/users/new.html.erb
<h1>Admin::Users#new</h1>
<p>Find me in app/views/admin/users/new.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Show page </h1>

<%= @user.full_name %> 
<%= @user.email %> <br>
<%= link_to "Log in as this User", admin_sessions_path(id: @user.id), method: :put %>
<hr>
<h4> <u>Reviews:</u> </h4><br>
<% @user.reviews.each do |review| %>
  <h5> <%= link_to review.movie.title, movie_path(review.movie) %> </h5>
  <p><%= review.text %></p>
  <p><%= review.rating_out_of_ten %>/10</p>
<% end %>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>