config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:create, :new, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
    resource :sessions, only: [:update]
  end

  

  

end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", sessions_path, method: :delete %>)
      <% if current_user.is_admin %>
        | <%= link_to "Admin Page", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_sessions_path %> | <%= link_to "Sign Up", new_user_path %> 
    <% end %>
    <% if current_admin && current_user != current_admin%>
      <%= link_to "Switch back to admin account", admin_sessions_path, method: :put %>
    <% end %>
  </small>
</footer>

app/views/layouts/_navbar.html.erb
<nav id="header-navbar" class="navbar navbar-inverse navbar-fixed-top navbar-transparent">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <button class="btn btn-link navbar-btn navbar-theme" onclick="location.href='/';">Home</button>
        <% if current_user %>
          <button id="logged" class="btn btn-link navbar-btn navbar-theme" onclick="location.href='/users/<%= current_user.id %>';"><%= current_user.full_name %>
          </button>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <button class="btn btn-link navbar-btn navbar-theme" onclick="location.href='#';">Logout</button>
        <% else %>
          <button class="btn btn-link navbar-btn navbar-theme" onclick="location.href='#';">Log In</button>
          <button class="btn btn-link navbar-btn navbar-theme" onclick="location.href='#';">Sign Up</button>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="flash-messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>